### ISSUE TITLE
useR2016 Online video for gtfsr?

### ISSUE THREAD

**Issue by hansthompson** [ropenscilabs/gtfsr#10]
I don't see the useR2016 talk available.  Did you not want to share it? 

https://channel9.msdn.com/Events/useR-international-R-User-conference/useR2016/gtfsr-A-package-to-make-transit-system-analysis-easy

**Comment by dantonnoriega** [comment]
It was a 5 min lighting talk. But sure if those were recorded?

**Comment by hansthompson** [comment]
I can't say for sure.  It just looks like there was a link and there are other lightning talks posted.
