### ISSUE TITLE
function to pull all versions of a feed

### ISSUE THREAD

**Issue by hansthompson** [ropenscilabs/gtfsr#13]
I just thought it might be neat to look across previous versions and summarize the changes some how. Not sure what would be best though.

**Comment by dantonnoriega** [comment]
That would be cool! Not sure if the API has this though... have you found a way to do this? Seems to just have the most recent data (and we aren't storing older versions).

**Comment by dantonnoriega** [comment]
Doesn't seem possible but will look into as I update the package!
