### ISSUE TITLE
Pass opacity variable to functions that call leaflet

### ISSUE THREAD

**Issue by hansthompson** [ropenscilabs/gtfsr#15]
Just thought it could be helpful sometimes when its hard to see it on the basemap.

**Comment by ultinomics** [comment]
I have a working branch `map-update` with a new option to change the opacity of stops (`stop_opacity`) but don't yet have one for route opacity. However, there is an option to hide route shapes by selecting `only_stops = TRUE`.

**Comment by dantonnoriega** [comment]
I have a working branch map-update with a new option to change the opacity of stops (stop_opacity) but don't yet have one for route opacity. However, there is an option to hide route shapes by selecting only_stops = TRUE.

Give it a go and let me know if it helps/works.

**Comment by dantonnoriega** [comment]
And now there is a `route_opacity` option!
