### ISSUE TITLE
validation in calendar.txt

### ISSUE THREAD

**Issue by hansthompson** [ropenscilabs/gtfsr#17]
I think if we parse the dates in calendar.txt with `strptime(foo, format = "%Y%m%d")` we can test if they fit the standard.  

And I think if we convert the fields for the days of the week with  `as.logical()` we can test if they are a value other than 0 or 1.

**Comment by hansthompson** [comment]
we could also do a visual validation of the times and dates from calendar.txt. Continuing from the vignette duke example 

```
nc$calendar_df %>% mutate(start_date = as.Date(start_date, format = "%Y%m%d"),
                          end_date = as.Date(end_date, format = "%Y%m%d")) %>%
  gather(key = start_or_end, value = date, start_date, end_date) %>%
  gather(key = day_of_week, value = on_this_day, monday, tuesday, wednesday, thursday, friday, saturday, sunday) %>%
  filter(on_this_day == 1) %>% 
  mutate(day_of_week = factor(day_of_week, 
                              levels = c("monday", "tuesday", "wednesday", "thursday", "friday", "saturday", "sunday"))) %>%
  ggplot() + geom_line(aes(x = date, y = service_name)) + 
  facet_wrap(~day_of_week)
```

**Comment by maelle** [comment]
This package is looking for a new maintainer or a new maintainer team. If you're interested, see #65. :smile_cat:
