### ISSUE TITLE
Couldn't render NYC subway lines

### ISSUE THREAD

**Issue by minhnhat992** [ropenscilabs/gtfsr#18]
Hi ,

I am researching about the NYC's subway system and came across the "gtfsr" package. It is a wonderful package, however, it wasn't able to render the shapes of many NYCs subway lines (E, 1, C , etc.). The error that I received is :

Error in `row.names<-.data.frame`(`*tmp*`, value = value) : 

  missing values in 'row.names' are not allowed

I suspect there might be something incorrect in the GTFS file. Do you have any recommendations to bypass these problems? Also, is the package capable of handling realtime data feed?

Below is the reproducible codes that I used:

```
feedlist_df <- get_feedlist() %>% 
  filter(grepl('NYC Subway GTFS',t, ignore.case= TRUE))

NYC <- import_gtfs(feedlist_df$url_d)

#get line A
route <- NYC[['routes_df']] %>% 
  slice(which(grepl('a', route_short_name, ignore.cas=TRUE)))

map_gtfs_route_shapes(gtfs_obj = NYC,
                     route_id = route$route_id,
                     include_stops = FALSE)
```

**Comment by dantonnoriega** [comment]
Thanks for the reproducible code! I was able to find the problem and fixed the issue.

Try removing/reinstall the package and give it a go!
