### ISSUE TITLE
Validation fails if `calendar.txt` is missing, but `calendar_dates.txt` exists

### ISSUE THREAD

**Issue by patperu** [ropenscilabs/gtfsr#20]
Hi,
this gtfs feed 

``` R
library("gtfsr")
gtfs <- import_gtfs("http://www.sardegnamobilita.it/opendata/dati_atpnu.zip")
```

is classified as `...failed. Invalid data structure.` 
This is because the file `calendar.txt` is missing - this is the relevant line:
https://github.com/ropenscilabs/gtfsr/blob/master/R/validate-gtfs-structure.R#L19

But according to the reference, you can omit `calendar.txt`  if `calendar_dates.txt` includes all dates of service, see https://developers.google.com/transit/gtfs/reference/calendar_dates-file

**Comment by dantonnoriega** [comment]
Great find. I'll update so that validation checks for this exception.

**Comment by dantonnoriega** [comment]
Fixed!
