### ISSUE TITLE
read_gtfs will delete invalid gtfs zip files. 

### ISSUE THREAD

**Issue by hansthompson** [ropenscilabs/gtfsr#28]
### read_gtfs will delete invalid gtfs zip files. 

I don't have permission to share the zipped gtfs in question but on opening it with read_gtfs it deletes the zip from my file system.  I'm using ubuntu 14.04.

**Comment by dantonnoriega** [comment]
This is the default action of the `read_gtfs`. I changed it to keep by default. Let me know if it keeps happening.
