### ISSUE TITLE
unzip_gtfs() wants to unzip to base directory

### ISSUE THREAD

**Issue by hansthompson** [ropenscilabs/gtfsr#3]
The first line of unzip_gtfs is 

`ex_dir <- strsplit(path, '/')[[1]][1]`

Assuming path is the filepath to gtfs_zip.zip this will assign the root directory of the user or operating system.

**Comment by dantonnoriega** [comment]
unzip_gtfs has been updated and now unzips to a temporary directory unless specified otherwise.
