### ISSUE TITLE
add docs for os-specific setup?

### ISSUE THREAD

**Issue by tbuckl** [ropenscilabs/gtfsr#36]
i had to do this before import_gtfs() would work today (windows 10 R 3.3)

```
install.packages("pkgconfig")
install.packages("glue")
install.packages("bindrcpp")
```

**Comment by tbuckl** [comment]
@dantonnoriega i can put this in the main doc if thats helpful. or if you want to link out to a secondary doc that works too.

**Comment by dantonnoriega** [comment]
weird. what packages needed those?

**Comment by tbuckl** [comment]
@dantonnoriega yeah i thought it was weird too--could be something with my env. let me check on another machine.

**Comment by tbuckl** [comment]
nevermind looks like this was an issue in my environment.
