### ISSUE TITLE
Calculating distance of each trip_id and shape_id

### ISSUE THREAD

**Issue by rafapereirabr** [ropenscilabs/gtfsr#37]
Hi Danton.

I would like to share this snippet of code that is super fast to calculate the distance of each shape_id. The idea is to use `data.table` to make really quick operations.

```
library(data.table)
library(geosphere)

# read shapes.txt
  shapes_df <- fread("shapes.txt)

# convert lat long columns to numeric
  shapes_df[, shape_pt_lon := as.numeric(shape_pt_lon) ][, shape_pt_lat := as.numeric(shape_pt_lat) ]

# Pair subsequent points for each shape
  shapes_df[, `:=`(next_shape_pt_sequence = shift(shape_pt_sequence, type = "lead"), 
                   next_lat = shift(shape_pt_lat, type = "lead"),
                   next_lon = shift(shape_pt_lon, type = "lead")), by = .(shape_id)]

# Calculate distance between each point in the shape
  shapes_df[ , shape_dist_traveled := distGeo(matrix(c(shape_pt_lon, shape_pt_lat), ncol = 2), 
                                              matrix(c(next_lon, next_lat), ncol = 2))/1000]

# sum total distance of each shape_id
  shapes_df[ , .(dist_shape= sum(shape_dist_traveled, na.rm=T)), by=shape_id]

#>      shape_id dist_shape
#> 1: 29647112  39.476308
#> 2: 17391142   7.941542
#> 3: 17614235  28.088435
#> 4: 29949632  14.276429
#> 5: 17576631   7.025251

```

Now what I do next is to add this info to the `trip.txt` file . I also do a similar operation in the `stop_times.txt` file to estimate the travel time between stops and the travel time for each trip. The idea in the end is to combine these results to get a diagnostic of each gtfs feed with the summary statistics (min, mean, max) of distance and speed for each trip and possibly and for ech trip segment between pairs of stops.

I still haven't find time to work on my scripts to contribute with new a function that gets this summary to the package. In the mean time, I hope this will snippet will be useful for other purposes as well.

**Comment by dantonnoriega** [comment]
I'm a big fan of `data.table` but chose to keep things consistent by using `tidy verse`.

Would you mind posting computation speeds between doing things in `data.table` vs `tidyverse`? If there difference are not too large, I think it's worth keeping it in `tidyverse`.

**Comment by SymbolixAU** [comment]
For what it's worth, you can speed up the geosphere calculations too (I think this may have been in answer to your SO question @rafapereirabr ) 
https://stackoverflow.com/a/42014364/5977215

(and I have been playing about with various spatial calculations within data.table: https://www.symbolix.com.au/blog-main/j26ynx6awfl32brcaxdjxnwalwmmbc)

**Comment by rafapereirabr** [comment]
@dantonnoriega , I can see why one would like to keep `tidyverse` consistency when it comes to the library interface with the end user but IMHO this needs to be flexible when the code running in back can be made more efficient.

Here is a simple benchmark comparing the two approaches using the gtfs feeds of NYC. Note that the `data.table` approach is almost two times faster than `dplyr`. This efficiency gain gets even larger if one wants to calculate travel times and merge different data sets, particularly when working with large GTFS feeds.

```
library(gtfsr)
library(magrittr)
library(data.table)
library(dplyr)

# import data
  set_api_key()  
  
  feedlist_df <- get_feedlist() %>% filter(grepl('NYC', t, ignore.case= TRUE))
  NYC <- import_gtfs(feedlist_df$url_d)

# Let's use @SymbolixAU dt.haversine function to calculate distance
  dt.haversine <- function(lat_from, lon_from, lat_to, lon_to, r = 6378137){
    radians <- pi/180
    lat_to <- lat_to * radians
    lat_from <- lat_from * radians
    lon_to <- lon_to * radians
    lon_from <- lon_from * radians
    dLat <- (lat_to - lat_from)
    dLon <- (lon_to - lon_from)
    a <- (sin(dLat/2)^2) + (cos(lat_from) * cos(lat_to)) * (sin(dLon/2)^2)
    return(2 * atan2(sqrt(a), sqrt(1 - a)) * r)
  }


# Create data.table and dplyr approach to calculate distances between points along each shape_id
  dt_fun <- function(df){ 
    
    # row bind shapes_df
    df <- sapply(NYC, '[[', "shapes_df") %>% rbindlist(fill=T)
    
    # calculate distances
    df[, shape_dist := dt.haversine(shape_pt_lat, shape_pt_lon, 
                                                          shift(shape_pt_lat, type = "lead"), 
                                                          shift(shape_pt_lon, type = "lead")), by=shape_id]
    
    # return total length of each shape_id
    df[, sum(shape_dist, na.rm=T), by=shape_id]
    
                                }
  
  
  
  dp_fun <- function(df){ 
    
    # row bind shapes_df
    df <- sapply(NYC, '[[', "shapes_df") %>% bind_rows()
    
    # calculate distances
    df  %<>%  group_by(shape_id) %>%
                                    mutate(shape_dist = dt.haversine(shape_pt_lat, shape_pt_lon, 
                                                                     lead(shape_pt_lat,1),
                                                                     lead(shape_pt_lon,1)))
    # return total length of each shape_id
    df  %>%  group_by(shape_id) %>% summarise( sum(shape_dist, na.rm=T))
      
                          }


m
#> Unit: milliseconds
#> expr       min        lq      mean    median       uq      max neval cld
#>   dt  77.05364  80.49646  89.69141  83.69189 100.2968 118.1793   100  a 
#>   dp 125.74620 130.24062 150.24058 145.90725 153.3972 383.6470   100   b
```

**Comment by mdsumner** [comment]
I think the inner sapply(NYC, ) in each function is unnecessary? You should be passing in shapes_df each time, right? 

BTW, I'm impressed how fast both dt and dp are, I thought this would beat it but I think it's the split that's slow: 

```R
res <- lapply(split(shapes_df[, c("shape_pt_lat", "shape_pt_lat")], shapes_df$shape_id), 
       function(x) sum(dt.haversine(head(x[[1]], -1), head(x[[2]], -1), tail(x[[1]], -1), tail(x[[2]], -1))))
aa <- tibble::tibble(shape_id = names(res), distance_km = unlist(res, use.names = FALSE))
```

I appreciate the example!

**Comment by rafapereirabr** [comment]
@mdsumner Some  metropolitan areas have different transit agencies that create separate GTFS feeds. So if one wants to analyze the entire transit system of an area,  it is important to consider all feeds at the same time. This is the reason why I used  `sapply(NYC, '[[', "shapes_df") %>% rbindlist(fill=T)` to bind all `shapes.txt` files.

**Comment by mdsumner** [comment]
But that happens outside the function, and then inside each function - and the `df` input to each function is ignored. So I'm still confused :{

**Comment by rafapereirabr** [comment]
Oops. My bad. I didn't see the code was repeating `sapply` inside and outside the function. Thanks for the heads ups. I've removed the `sapply` call outside the functions

**Comment by dantonnoriega** [comment]
I generalized the code just in case one doesn't want to combine all shape files and to ensure all functions are self contained (do not depend on objects not passed to function). I also thought that, perhaps, converted objects may contribute to slowdown.

The conversion appears to have minimal impact. And `data.table` is faster (which isn't surprising).

So the question is:

> Add another package dependency or get the speed boost?

I suppose adding another dependency isn't that big a deal. **I think the question is more _what do you all want as users_**? 

```
library(gtfsr)
library(magrittr)
library(data.table)
library(dplyr)
library(microbenchmark)

# Let's use @SymbolixAU dt.haversine function to calculate distance
dt.haversine <- function(lat_from, lon_from, lat_to, lon_to, r = 6378137){
  radians <- pi/180
  lat_to <- lat_to * radians
  lat_from <- lat_from * radians
  lon_to <- lon_to * radians
  lon_from <- lon_from * radians
  dLat <- (lat_to - lat_from)
  dLon <- (lon_to - lon_from)
  a <- (sin(dLat/2)^2) + (cos(lat_from) * cos(lat_to)) * (sin(dLon/2)^2)
  return(2 * atan2(sqrt(a), sqrt(1 - a)) * r)
}


# Create data.table and dplyr approach to calculate distances between points along each shape_id
dt_fun <- function(df) {

  if(!"data.table" %in% class(df))
    df <- as.data.table(df) # convert to data.table if not

  # calculate distances
  df[, shape_dist := dt.haversine(shape_pt_lat, shape_pt_lon,
    shift(shape_pt_lat, type = "lead"),
    shift(shape_pt_lon, type = "lead")), by="shape_id"]

  # return total length of each shape_id
  df[, .(len = sum(shape_dist, na.rm=T)), by=shape_id]

}

dp_fun <- function(df) {

  if(!"tbl_df" %in% class(df))
    df <- as_tibble(df) # convert to tibble if not

  # calculate distances
  df  %<>%
    group_by(shape_id) %>%
    mutate(shape_dist = dt.haversine(shape_pt_lat, shape_pt_lon,
       lead(shape_pt_lat,1),
       lead(shape_pt_lon,1)))

  # return total length of each shape_id
  df %>%
    group_by(shape_id) %>%
    summarise(len = sum(shape_dist, na.rm=T))
}

# get nyc data
feedlist_df <- get_feedlist() %>% filter(grepl('NYC', t, ignore.case= TRUE))
NYC <- import_gtfs(feedlist_df$url_d)

# get shape_dfs. filter out missing data from incomplete urls.
shapes_df <- lapply(NYC, '[[', "shapes_df") %>%
  .[sapply(., function(x) !is.null(x))]

# create data.table shapes
dt_sh <- shapes_df %>%
  lapply(., as.data.table)

# create tibble shapes
dp_sh <- shapes_df %>%
  lapply(., as_tibble)

# create functions
f1 <- function(x) lapply(x, dt_fun) # using dt
f2 <- function(x) lapply(x, dp_fun) # using dp

# compare
microbenchmark(f1(dt_sh), f1(dp_sh), #f1 with and without conversion
  f2(dt_sh), f2(dp_sh), times = 50) #f2 with and without conversion
```

Output:
```
Unit: milliseconds
      expr      min       lq      mean    median        uq      max neval cld
 f1(dt_sh) 42.59402 56.65305  71.53837  64.31160  84.47687 256.0073   300  a
 f1(dp_sh) 46.01183 55.13813  69.05993  67.17474  77.86111 250.9426   300  a
 f2(dt_sh) 89.20765 98.25594 116.99127 114.91747 127.40416 275.4115   300   b
 f2(dp_sh) 87.73844 96.08355 114.90429 113.12097 123.27309 294.1482   300   b
```

**Comment by mdsumner** [comment]
Oh nice, thanks!

**Comment by rafapereirabr** [comment]
@dantonnoriega , nice work but prefer converting DFs into data.table using `setDT(df)` instead of `as.data.table(df)`. because it's much faster.

I've already written a function that  returns the travelled distance, speed and travel time for each `trip_id`. My code also aggregates (average) this info to `route_id` level and counts the frequency of each `route_id` as well. I find this useful to check consistency of a GTFS feed and to map the transit network with routes colored according to speed, frequency etc.

I thought others might find it useful as well, and that's why I opened this issue.

**Comment by dantonnoriega** [comment]
I think it is very useful. Let's open a `dev` branch and start adding some functions!

**Comment by mdsumner** [comment]
Agreed! And for what it's worth - I'm here just as interested observer, it's very useful for me to see these explorations. I don't have enough understanding of gtfsr broadly to weigh up pros and cons overall.

**Comment by mdsumner** [comment]
FWIW, I'd go with the non-data.table approach and seek speed ups when needed - there's a lot of options and it's kind of easier to make decisions about a package that's already released ;)

**Comment by dantonnoriega** [comment]
@rafapereirabr been a while but I was wondering if you were still interested in adding your functions to the package for calculating distances?

**Comment by rafapereirabr** [comment]
@dantonnoriega , I would be glad to contribute with that function. This month is quite busy for me though as I'm trying to submit my thesis asap. Is it Ok I make this contribution in early July?

**Comment by dantonnoriega** [comment]
No rush, dude!

**Comment by r-barnes** [comment]
But this method leaves out the possibility that the road distance between two stops is significantly longer than the great circle distance.

**Comment by rafapereirabr** [comment]
In hindsight,  I believe a function calculating distances between stops should ideally consider the network distance along the route. I haven't found a fast way to do this, though. Any thoughts?

**Comment by SymbolixAU** [comment]
it will require the `shapes.txt` file to give you the network, then it should be a case of iterating along the coordinates in the shape and finding the distance between each one, and summing them up as you go. Do this in C++ and it should be fast.

**Comment by mdsumner** [comment]
dodgr?

**Comment by SymbolixAU** [comment]
For routes or distance?

**Comment by polettif** [comment]
Just as a general FYI, [pfaedle](https://github.com/ad-freiburg/pfaedle) is a tool to create shapes.txt with network routes if a feed doesn't have them already.

**Comment by SymbolixAU** [comment]
@polettif that looks very useful. Do you know if there are any plans to wrap it in an R library?

**Comment by polettif** [comment]
No, I don't know of any plans. I guess it shouldn't be too difficult with Rcpp.

**Comment by maelle** [comment]
This package is looking for a new maintainer or a new maintainer team. If you're interested, see #65. :smile_cat:
