### ISSUE TITLE
Dealing with irregular, unrecognised GTFS files

### ISSUE THREAD

**Issue by phildonovan** [ropenscilabs/gtfsr#38]
Hey guys,

I *think* the Auckland GTFS feed fails when importing the non-conforming GTFS file called stops_info.txt. Here is the reproducible code:

    akl_url <- get_feedlist() %>% 
      filter(grepl("Auckland Transport GTFS", t)) %>% 
      pull(url_d)

    akl_gtfs <- import_gtfs(akl_url)

I assume it is as easy as adding in a check, and an option for ignoring irregular files e.g. files not in the google specification? I'm happy to go try doing this but I am relatively new to the package writing world. Happy to receive some guidance.

Cheers,
Phil Donovan

**Comment by tbuckl** [comment]
hi @phildonovan i see that too. tried to email you but your listed github email is dead.

**Comment by dantonnoriega** [comment]
I was able to recreate the error, but here is my question:

do you happen to know if there is a general format for `stop_info.txt`. Googling the file name results in no standard file result. But I did find a single occurrence of the file online... [Auckland](https://transitfeeds.com/p/auckland-transport/124/20170315/file/stop_info.txt)! 

That said, the broader concern that you bring up is the fact that the package shouldn't fail to load all standard file formats if it encounters an unknown file.

I'll add a line to ensure the package still imports data even when it encounters such a file.

**Comment by dantonnoriega** [comment]
@phildonovan please download the most recent version and tell me if it fixes your problem. Works on my end!

**Comment by dantonnoriega** [comment]
assumed fixed?
