### ISSUE TITLE
GTFS Realtime

### ISSUE THREAD

**Issue by SymbolixAU** [ropenscilabs/gtfsr#39]
I've got a much more nascent gtfs package where I've been focusing on getting the realtime feeds into R, (and integrating with `data.table`). 
https://github.com/SymbolixAU/gtfsway

Is this something you think is worthwhile bringing into `gtfsr` ?

**Comment by dantonnoriega** [comment]
Apologies for not responding sooner. It’s something I considered long ago but had to shift away from this project. 

Feel free to hack away and see if you could add it as a feature!

**Comment by mdsumner** [comment]
@SymbolixAU - I haven't compared with your work, but you might like to see https://twitter.com/sjmgarnier/status/963248599982395392 and https://ropensci.org/blog/2017/11/14/realtime/

**Comment by SymbolixAU** [comment]
@dantonnoriega Not to worry, I have also shifted away. I might get back to it at some point, but I have other priorities.

@mdsumner thanks for the links - I was aware of the output from the OzUnconf, and in particular tRainspotting (even though they say my project doesn't have a nice name https://github.com/ropenscilabs/tRainspotting ) - the cheek ;)

**Comment by maelle** [comment]
This package is looking for a new maintainer or a new maintainer team. If you're interested, see #65. :smile_cat:
