### ISSUE TITLE
cran release

### ISSUE THREAD

**Issue by mpadge** [ropenscilabs/gtfsr#45]
Both a question and a prompt: Any concrete plans? Schedule?

I'll be happy to help any way I can. Maybe start a git project, add some issues to it, and ask folk to jump in and help? I would like to use`gtfsr ` in an extension to my [`dodgr` package](https://github.com/ATFutures/dodgr), but would need it on CRAN first.

**Comment by mdsumner** [comment]
I'll help!

**Comment by dantonnoriega** [comment]
I think a big missing part is examples and documentation. I’d love help.
New job plus still working on dissertation has limited extra time.

**Comment by mpadge** [comment]
Those are 2 good excuses. Expect some PRs soon then

**Comment by tbuckl** [comment]
hi @mpadge @dantonnoriega @mdsumner. 

i've been looking at functions like this:

https://github.com/ropensci/gtfsr/blob/master/R/map-gtfs-stop.R

i hope to have a relevant vignette on something related to contribute within a few days.

**Comment by maelle** [comment]
This package is looking for a new maintainer or a new maintainer team. If you're interested, see #65. :smile_cat:
