### ISSUE TITLE
Add names of recent contributors to description

### ISSUE THREAD

**Issue by dantonnoriega** [ropenscilabs/gtfsr#51]
To all who have contributed recently, please leave your preferred name and, optionally, email, as a comment below so your contributions can be recognized!

**Comment by mdsumner** [comment]
Michael Sumner, don't really feel like it was much, but hope to do more, thanks!

**Comment by tbuckl** [comment]
Tom Buckley. buckley.tom@gmail.com

**Comment by dantonnoriega** [comment]
Thanks. Added you guys to the DESCRIPTION.
