### ISSUE TITLE
consider breaking off pieces of the package that make maintenance and CRAN submission harder

### ISSUE THREAD

**Issue by tbuckl** [ropenscilabs/gtfsr#53]
hi @dantonnoriega, @mpadge, and @mdsumner, 

i'd be grateful if you could give me some feedback on attempt i made to refactor this package so that it can keep on chugging along. 

i broke things out by function/dependency:

https://github.com/r-gtfs

i think gtfsr can still live here and will require a lot less code in it.  let me know what you think, if you have the time. 

i think this may offer a few simple solutions to https://github.com/ropensci/gtfsr/issues/45 and https://github.com/ropensci/gtfsr/issues/48

i also hope having these component pieces should make issue like https://github.com/ropensci/gtfsr/issues/29 easier for people to contribute to. 

thanks for taking a look.

**Comment by mpadge** [comment]
This looks like a really sound approach, nice work @tbuckl. Especially the quarantining-off of `gtfs` is really sensible and likely very advantageous. I'm travelling a lot over summer (as is @mdsumner), so likely won't have too much time for the next month or so, but will get on to it asap after that. Feel free in the meantime to ping any issues, questions, thoughts. This is a great development!

**Comment by mpadge** [comment]
Also ping @robinlovelace

**Comment by tbuckl** [comment]
thanks @mpadge yes the primary concern was to isolate a few things:

1) transitfeeds.com (could replace, augment with transit.land or, in bay area, 511). 
2) reading and writing gtfs files from urls (this seems really solid, well tested).
3) geospatial data types (could replace sf with sp or silicate)
4) mapping (let other packages handle the hard stuff--tmap, mapview)
5) schedules/time analysis 

i think (1), (2), and (5) could probably live together happily. and maybe (3) and (4) too. 

but perhaps its an opportunity to distribute CRAN-management too. i look to you all for guidance on that as i don't have much experience with CRAN.

**Comment by mpadge** [comment]
I think that initial fragmentation into sensible smallest possible units is a great idea. We will gain pretty speedy insight into the extent of code overlap/re-use between the components, and that will likely provide the best guide to future re-mergers.

**Comment by angela-li** [comment]
Hi all! I've been using `gtfsr` lately for work, and I have a pretty clear idea of how this package could be split up for maintenance and submission to CRAN. 

To me, it makes sense to keep `gtfsr` as a package solely for ETL and API access to TransitFeeds, and make a **single separate package** that imports `gtfsr` (called `tidytransit`, possibly modeled after [`tidycensus`](https://github.com/walkerke/tidycensus)) that allows transportation analysts/planners to get GTFS data they need in a useful format. Having a single package that returns useful tibbles will make it easier for new users to get value out of using R for transit analysis.

I saw the experimental refactoring work @tbuckl has been doing with r-transit, and I think it's awesome that he's taken initiative on this. However, in terms of next steps, I think we should:

1. build out a working `tidytransit` package that's super easy to use, along with clear documentation and examples. I've mapped out 4 functions for this package that would make it the most valuable for me - @tbuckl maybe we can discuss?

2. come back to `gtfsr` and clean out any functions that don't directly relate to ETL / validation, stripping it down to what it does best: importing GTFS feeds into R and checking 'em!

3. (in the near future...) submit both `gtfsr` and `tidytransit` to CRAN as a combined suite of transit tools for R.

I'll have time to work on this in the next few weeks/months and would love to see this take off!

**Comment by znmeb** [comment]
I'm building some GTFS consumption tools and I ended up using the Python-based ones that feed directly into a relational database - https://github.com/CUTR-at-USF/gtfsrdb for the real-time feed and https://github.com/OpenTransitTools/gtfsdb for the schedule feed. Considering the magnitude of these feeds, this approach made more sense than `gtfsr` and https://github.com/SymbolixAU/gtfsway.

My ideal tool (at least for TriMet here in Portland) would acquire and log to disk all three real-time feeds (they're three separate URLs here) as tidy data frames / streams and only deal with the huge main GTFS dataset for necessary joins, like the route "shapefiles" and scheduled arrival times.

**Comment by tbuckl** [comment]
hi @angela-li thanks. i'm going to close this issue. i largely satisfied this request for myself here:

https://github.com/r-transit

as you know, `tidytransit` is an existing package name. so another package named exactly the same thing might make things difficult for users. 

perhaps given that you work for @eamcvey, the listed maintainer, she can give you the direction you need on your goals.
