### ISSUE TITLE
trouble installing on windows and rstudio.cloud

### ISSUE THREAD

**Issue by DustinAlandzes** [ropenscilabs/gtfsr#57]
Hey! I'm trying to reproduce [this visualization](https://www.dfsnow.me/post/r-gtfs-feeds/) using [my own gtfs data](https://www.viainfo.net/developers-resources/) and one of the dependecies is gtfsr. However the install gets hung up on a dependency called 'gtsf', any ideas? I've tried on windows (r version 3.5.1) and rstudio cloud (r version 3.5.0) so far.

Sorry if I'm missing something obvious! Thanks for reading

```
> devtools::install_github('ropensci/gtfsr')
Downloading GitHub repo ropensci/gtfsr@master
from URL https://api.github.com/repos/ropensci/gtfsr/zipball/master
Installing gtfsr
'/opt/R/3.5.0/lib/R/bin/R' --no-site-file --no-environ --no-save --no-restore --quiet  \
  CMD INSTALL '/tmp/RtmpMARBVQ/devtoolsd524ffa48f/ropensci-gtfsr-05111e1'  \
  --library='/home/rstudio-user/R/x86_64-pc-linux-gnu-library/3.5' --install-tests 

ERROR: dependency ‘gtsf’ is not available for package ‘gtfsr’
* removing ‘/home/rstudio-user/R/x86_64-pc-linux-gnu-library/3.5/gtfsr’
Installation failed: Command failed (1)
```

**Comment by dantonnoriega** [comment]
I checked an this is due to `gtsf` being deprecated. I also checked and this dependency was unnecessary. Made a few quick edits. Should work now but I have yet to test (other than a successful install on my local machine).
