### ISSUE TITLE
API key

### ISSUE THREAD

**Issue by baltti** [ropenscilabs/gtfsr#63]
Neither transitfeed.com nor openmobilitydata.com sign in works and it is impossible to obtain their API key. 
Do you know anything about other possibilities of getting API key? Do they still support it?

**Comment by pkbenoliel** [comment]
Hello,

It seems openmobilitydata.com is being moved to a site called 'mobility database':

https://database.mobilitydata.org/

I haven't done a lot of exploring yet, but it seems that openmobilitydata.com won't be issuing keys anymore.

**Comment by maelle** [comment]
This package is looking for a new maintainer or a new maintainer team. If you're interested, see #65. :smile_cat:
