### ISSUE TITLE
Is this package still maintained?

### ISSUE THREAD

**Issue by maelle** [ropenscilabs/gtfsr#64]
:wave: @dantonnoriega et al! Is this package still maintained?

I see errors https://github.com/r-universe/ropensci/runs/6549341600?check_suite_focus=true via https://ropensci.r-universe.dev/ui#builds=

**Comment by dantonnoriega** [comment]
Im no longer maintaining. I wish I had the bandwidth to do so! Would love to find someone who'd like to do so but I'm disconnected from the transportation space quite a bit these days.

**Comment by maelle** [comment]
Thanks a lot @dantonnoriega, I'll add a call for new maintainers in different channels including the newsletter.

**Comment by maelle** [comment]
#65
