### ISSUE TITLE
New Maintainer Wanted :-)

### ISSUE THREAD

**Issue by maelle** [ropenscilabs/gtfsr#65]
Or a new maintainer _team_ :smile_cat: 

If you're interested, please comment in the issue. 
For more info, see

* [our guidance on _Changing package maintainers_](https://devguide.ropensci.org/changing-maintainers.html);
* [our _Package Curation Policy_](https://devguide.ropensci.org/curationpolicy.html).

**Comment by mpadge** [comment]
This package has actually evolved into the non-rOpenSci package https://github.com/r-transit/tidytransit, which is actively maintained and developed. I think this pacakge should be archived. @dantonnoriega would you be okay with us archiving this package, and putting a pointer on a reduced README to tidytransit?

**Comment by maelle** [comment]
@mpadge could you please transform the README (so that you might phrase the pointer to tidytransit)? Thank you!

**Comment by mpadge** [comment]
Sorry @maelle i tried but don't have admin here. But you can just copy-paste this:

``` md
# gtfsr

[![Project Status: Unsupported](https://www.repostatus.org/badges/latest/unsupported.svg)](https://www.repostatus.org/#unsupported)

This package has been archived, with ongoing developed moved to [r-transit/tidytransit](https://github.com/r-transit/tidytransit). The former README is now in [README-NOT.md](README-NOT.md).
```

**Comment by maelle** [comment]
This package has been archived, with ongoing developed moved to [r-transit/tidytransit](https://github.com/r-transit/tidytransit).
